// Code generated by protoc-gen-go.
// source: peer/chaincodeshim.proto
// DO NOT EDIT!

package peer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ChaincodeMessage_Type int32

const (
	ChaincodeMessage_UNDEFINED                    ChaincodeMessage_Type = 0
	ChaincodeMessage_REGISTER                     ChaincodeMessage_Type = 1
	ChaincodeMessage_REGISTERED                   ChaincodeMessage_Type = 2
	ChaincodeMessage_INIT                         ChaincodeMessage_Type = 3
	ChaincodeMessage_READY                        ChaincodeMessage_Type = 4
	ChaincodeMessage_TRANSACTION                  ChaincodeMessage_Type = 5
	ChaincodeMessage_COMPLETED                    ChaincodeMessage_Type = 6
	ChaincodeMessage_ERROR                        ChaincodeMessage_Type = 7
	ChaincodeMessage_GET_STATE                    ChaincodeMessage_Type = 8
	ChaincodeMessage_PUT_STATE                    ChaincodeMessage_Type = 9
	ChaincodeMessage_DEL_STATE                    ChaincodeMessage_Type = 10
	ChaincodeMessage_INVOKE_CHAINCODE             ChaincodeMessage_Type = 11
	ChaincodeMessage_GET_K_STATE_BY_MULTIPLE_KEYS ChaincodeMessage_Type = 12
	ChaincodeMessage_RESPONSE                     ChaincodeMessage_Type = 13
	ChaincodeMessage_GET_STATE_BY_RANGE           ChaincodeMessage_Type = 14
	ChaincodeMessage_GET_QUERY_RESULT             ChaincodeMessage_Type = 15
	ChaincodeMessage_QUERY_STATE_NEXT             ChaincodeMessage_Type = 16
	ChaincodeMessage_QUERY_STATE_CLOSE            ChaincodeMessage_Type = 17
	ChaincodeMessage_KEEPALIVE                    ChaincodeMessage_Type = 18
	ChaincodeMessage_GET_HISTORY_FOR_KEY          ChaincodeMessage_Type = 19
)

var ChaincodeMessage_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "REGISTER",
	2:  "REGISTERED",
	3:  "INIT",
	4:  "READY",
	5:  "TRANSACTION",
	6:  "COMPLETED",
	7:  "ERROR",
	8:  "GET_STATE",
	9:  "PUT_STATE",
	10: "DEL_STATE",
	11: "INVOKE_CHAINCODE",
	12: "GET_K_STATE_BY_MULTIPLE_KEYS",
	13: "RESPONSE",
	14: "GET_STATE_BY_RANGE",
	15: "GET_QUERY_RESULT",
	16: "QUERY_STATE_NEXT",
	17: "QUERY_STATE_CLOSE",
	18: "KEEPALIVE",
	19: "GET_HISTORY_FOR_KEY",
}
var ChaincodeMessage_Type_value = map[string]int32{
	"UNDEFINED":                    0,
	"REGISTER":                     1,
	"REGISTERED":                   2,
	"INIT":                         3,
	"READY":                        4,
	"TRANSACTION":                  5,
	"COMPLETED":                    6,
	"ERROR":                        7,
	"GET_STATE":                    8,
	"PUT_STATE":                    9,
	"DEL_STATE":                    10,
	"INVOKE_CHAINCODE":             11,
	"GET_K_STATE_BY_MULTIPLE_KEYS": 12,
	"RESPONSE":                     13,
	"GET_STATE_BY_RANGE":           14,
	"GET_QUERY_RESULT":             15,
	"QUERY_STATE_NEXT":             16,
	"QUERY_STATE_CLOSE":            17,
	"KEEPALIVE":                    18,
	"GET_HISTORY_FOR_KEY":          19,
}

func (x ChaincodeMessage_Type) String() string {
	return proto.EnumName(ChaincodeMessage_Type_name, int32(x))
}
func (ChaincodeMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 0} }

type ChaincodeMessage struct {
	Type      ChaincodeMessage_Type       `protobuf:"varint,1,opt,name=type,enum=protos.ChaincodeMessage_Type" json:"type,omitempty"`
	Timestamp *google_protobuf1.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Payload   []byte                      `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Txid      string                      `protobuf:"bytes,4,opt,name=txid" json:"txid,omitempty"`
	Proposal  *Proposal                   `protobuf:"bytes,5,opt,name=proposal" json:"proposal,omitempty"`
	// event emmited by chaincode. Used only with Init or Invoke.
	// This event is then stored (currently)
	// with Block.NonHashData.TransactionResult
	ChaincodeEvent *ChaincodeEvent `protobuf:"bytes,6,opt,name=chaincode_event,json=chaincodeEvent" json:"chaincode_event,omitempty"`
}

func (m *ChaincodeMessage) Reset()                    { *m = ChaincodeMessage{} }
func (m *ChaincodeMessage) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeMessage) ProtoMessage()               {}
func (*ChaincodeMessage) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *ChaincodeMessage) GetTimestamp() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ChaincodeMessage) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func (m *ChaincodeMessage) GetChaincodeEvent() *ChaincodeEvent {
	if m != nil {
		return m.ChaincodeEvent
	}
	return nil
}

type PutStateInfo struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *PutStateInfo) Reset()                    { *m = PutStateInfo{} }
func (m *PutStateInfo) String() string            { return proto.CompactTextString(m) }
func (*PutStateInfo) ProtoMessage()               {}
func (*PutStateInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

type GetKStateByMultipleKeysResponse struct {
	KeyStates map[string][]byte `protobuf:"bytes,1,rep,name=keyStates" json:"keyStates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *GetKStateByMultipleKeysResponse) Reset()                    { *m = GetKStateByMultipleKeysResponse{} }
func (m *GetKStateByMultipleKeysResponse) String() string            { return proto.CompactTextString(m) }
func (*GetKStateByMultipleKeysResponse) ProtoMessage()               {}
func (*GetKStateByMultipleKeysResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *GetKStateByMultipleKeysResponse) GetKeyStates() map[string][]byte {
	if m != nil {
		return m.KeyStates
	}
	return nil
}

type GetStateByRange struct {
	StartKey string `protobuf:"bytes,1,opt,name=startKey" json:"startKey,omitempty"`
	EndKey   string `protobuf:"bytes,2,opt,name=endKey" json:"endKey,omitempty"`
}

func (m *GetStateByRange) Reset()                    { *m = GetStateByRange{} }
func (m *GetStateByRange) String() string            { return proto.CompactTextString(m) }
func (*GetStateByRange) ProtoMessage()               {}
func (*GetStateByRange) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

type GetQueryResult struct {
	Query string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
}

func (m *GetQueryResult) Reset()                    { *m = GetQueryResult{} }
func (m *GetQueryResult) String() string            { return proto.CompactTextString(m) }
func (*GetQueryResult) ProtoMessage()               {}
func (*GetQueryResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

type GetHistoryForKey struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *GetHistoryForKey) Reset()                    { *m = GetHistoryForKey{} }
func (m *GetHistoryForKey) String() string            { return proto.CompactTextString(m) }
func (*GetHistoryForKey) ProtoMessage()               {}
func (*GetHistoryForKey) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

type QueryStateNext struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *QueryStateNext) Reset()                    { *m = QueryStateNext{} }
func (m *QueryStateNext) String() string            { return proto.CompactTextString(m) }
func (*QueryStateNext) ProtoMessage()               {}
func (*QueryStateNext) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

type QueryStateClose struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *QueryStateClose) Reset()                    { *m = QueryStateClose{} }
func (m *QueryStateClose) String() string            { return proto.CompactTextString(m) }
func (*QueryStateClose) ProtoMessage()               {}
func (*QueryStateClose) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

type QueryStateKeyValue struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *QueryStateKeyValue) Reset()                    { *m = QueryStateKeyValue{} }
func (m *QueryStateKeyValue) String() string            { return proto.CompactTextString(m) }
func (*QueryStateKeyValue) ProtoMessage()               {}
func (*QueryStateKeyValue) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

type QueryStateResponse struct {
	KeysAndValues []*QueryStateKeyValue `protobuf:"bytes,1,rep,name=keys_and_values,json=keysAndValues" json:"keys_and_values,omitempty"`
	HasMore       bool                  `protobuf:"varint,2,opt,name=has_more,json=hasMore" json:"has_more,omitempty"`
	Id            string                `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *QueryStateResponse) Reset()                    { *m = QueryStateResponse{} }
func (m *QueryStateResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryStateResponse) ProtoMessage()               {}
func (*QueryStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *QueryStateResponse) GetKeysAndValues() []*QueryStateKeyValue {
	if m != nil {
		return m.KeysAndValues
	}
	return nil
}

func init() {
	proto.RegisterType((*ChaincodeMessage)(nil), "protos.ChaincodeMessage")
	proto.RegisterType((*PutStateInfo)(nil), "protos.PutStateInfo")
	proto.RegisterType((*GetKStateByMultipleKeysResponse)(nil), "protos.GetKStateByMultipleKeysResponse")
	proto.RegisterType((*GetStateByRange)(nil), "protos.GetStateByRange")
	proto.RegisterType((*GetQueryResult)(nil), "protos.GetQueryResult")
	proto.RegisterType((*GetHistoryForKey)(nil), "protos.GetHistoryForKey")
	proto.RegisterType((*QueryStateNext)(nil), "protos.QueryStateNext")
	proto.RegisterType((*QueryStateClose)(nil), "protos.QueryStateClose")
	proto.RegisterType((*QueryStateKeyValue)(nil), "protos.QueryStateKeyValue")
	proto.RegisterType((*QueryStateResponse)(nil), "protos.QueryStateResponse")
	proto.RegisterEnum("protos.ChaincodeMessage_Type", ChaincodeMessage_Type_name, ChaincodeMessage_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ChaincodeSupport service

type ChaincodeSupportClient interface {
	Register(ctx context.Context, opts ...grpc.CallOption) (ChaincodeSupport_RegisterClient, error)
}

type chaincodeSupportClient struct {
	cc *grpc.ClientConn
}

func NewChaincodeSupportClient(cc *grpc.ClientConn) ChaincodeSupportClient {
	return &chaincodeSupportClient{cc}
}

func (c *chaincodeSupportClient) Register(ctx context.Context, opts ...grpc.CallOption) (ChaincodeSupport_RegisterClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ChaincodeSupport_serviceDesc.Streams[0], c.cc, "/protos.ChaincodeSupport/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &chaincodeSupportRegisterClient{stream}
	return x, nil
}

type ChaincodeSupport_RegisterClient interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ClientStream
}

type chaincodeSupportRegisterClient struct {
	grpc.ClientStream
}

func (x *chaincodeSupportRegisterClient) Send(m *ChaincodeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chaincodeSupportRegisterClient) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ChaincodeSupport service

type ChaincodeSupportServer interface {
	Register(ChaincodeSupport_RegisterServer) error
}

func RegisterChaincodeSupportServer(s *grpc.Server, srv ChaincodeSupportServer) {
	s.RegisterService(&_ChaincodeSupport_serviceDesc, srv)
}

func _ChaincodeSupport_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChaincodeSupportServer).Register(&chaincodeSupportRegisterServer{stream})
}

type ChaincodeSupport_RegisterServer interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ServerStream
}

type chaincodeSupportRegisterServer struct {
	grpc.ServerStream
}

func (x *chaincodeSupportRegisterServer) Send(m *ChaincodeMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chaincodeSupportRegisterServer) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChaincodeSupport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ChaincodeSupport",
	HandlerType: (*ChaincodeSupportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _ChaincodeSupport_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor3,
}

func init() { proto.RegisterFile("peer/chaincodeshim.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 859 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x95, 0x51, 0x6f, 0xe2, 0x46,
	0x10, 0xc7, 0xcf, 0x04, 0x12, 0x98, 0x10, 0xd8, 0xdb, 0x5c, 0x53, 0x1f, 0x6a, 0x75, 0xd4, 0xaa,
	0x2a, 0x2a, 0x55, 0xd0, 0xa6, 0xd2, 0xe9, 0x54, 0x9d, 0x54, 0x11, 0xd8, 0x10, 0x0b, 0x30, 0xdc,
	0xda, 0x44, 0x47, 0x5f, 0x2c, 0x07, 0x26, 0x60, 0x05, 0xb0, 0xeb, 0x5d, 0x4e, 0xe7, 0xe7, 0xbe,
	0xf4, 0x0b, 0xf5, 0x43, 0xf5, 0x5b, 0x54, 0x6b, 0x63, 0x92, 0x34, 0x3a, 0xdd, 0x3d, 0xe1, 0xff,
	0xcc, 0x6f, 0xfe, 0x33, 0xe3, 0xb5, 0x16, 0xd0, 0x43, 0xc4, 0xa8, 0x35, 0x5b, 0x7a, 0xfe, 0x66,
	0x16, 0xcc, 0x51, 0x2c, 0xfd, 0x75, 0x33, 0x8c, 0x02, 0x19, 0xd0, 0xc3, 0xe4, 0x47, 0xd4, 0x5e,
	0x3e, 0x26, 0xf0, 0x03, 0x6e, 0x64, 0x8a, 0xd4, 0x4e, 0x93, 0x54, 0x18, 0x05, 0x61, 0x20, 0xbc,
	0xd5, 0x2e, 0xf8, 0x6a, 0x11, 0x04, 0x8b, 0x15, 0xb6, 0x12, 0x75, 0xb3, 0xbd, 0x6d, 0x49, 0x7f,
	0x8d, 0x42, 0x7a, 0xeb, 0x30, 0x05, 0x8c, 0xbf, 0x0b, 0x40, 0x3a, 0x99, 0xdd, 0x10, 0x85, 0xf0,
	0x16, 0x48, 0x7f, 0x81, 0xbc, 0x8c, 0x43, 0xd4, 0xb5, 0xba, 0xd6, 0xa8, 0x9c, 0x7f, 0x9b, 0xa2,
	0xa2, 0xf9, 0x7f, 0xae, 0xe9, 0xc4, 0x21, 0xf2, 0x04, 0xa5, 0x6f, 0xa0, 0xb4, 0xb7, 0xd6, 0x73,
	0x75, 0xad, 0x71, 0x7c, 0x5e, 0x6b, 0xa6, 0xcd, 0x9b, 0x59, 0xf3, 0xa6, 0x93, 0x11, 0xfc, 0x1e,
	0xa6, 0x3a, 0x1c, 0x85, 0x5e, 0xbc, 0x0a, 0xbc, 0xb9, 0x7e, 0x50, 0xd7, 0x1a, 0x65, 0x9e, 0x49,
	0x4a, 0x21, 0x2f, 0x3f, 0xfa, 0x73, 0x3d, 0x5f, 0xd7, 0x1a, 0x25, 0x9e, 0x3c, 0xd3, 0x9f, 0xa0,
	0x98, 0xad, 0xa8, 0x17, 0x92, 0x36, 0x24, 0x1b, 0x6f, 0xbc, 0x8b, 0xf3, 0x3d, 0x41, 0x7f, 0x87,
	0xea, 0xfe, 0x5d, 0xb9, 0xc9, 0xcb, 0xd2, 0x0f, 0x93, 0xa2, 0xb3, 0x27, 0x3b, 0x31, 0x95, 0xe5,
	0x95, 0xd9, 0x23, 0x6d, 0xfc, 0x9b, 0x83, 0xbc, 0xda, 0x92, 0x9e, 0x40, 0x69, 0x62, 0x75, 0xd9,
	0xa5, 0x69, 0xb1, 0x2e, 0x79, 0x46, 0xcb, 0x50, 0xe4, 0xac, 0x67, 0xda, 0x0e, 0xe3, 0x44, 0xa3,
	0x15, 0x80, 0x4c, 0xb1, 0x2e, 0xc9, 0xd1, 0x22, 0xe4, 0x4d, 0xcb, 0x74, 0xc8, 0x01, 0x2d, 0x41,
	0x81, 0xb3, 0x76, 0x77, 0x4a, 0xf2, 0xb4, 0x0a, 0xc7, 0x0e, 0x6f, 0x5b, 0x76, 0xbb, 0xe3, 0x98,
	0x23, 0x8b, 0x14, 0x94, 0x65, 0x67, 0x34, 0x1c, 0x0f, 0x98, 0xc3, 0xba, 0xe4, 0x50, 0xa1, 0x8c,
	0xf3, 0x11, 0x27, 0x47, 0x2a, 0xd3, 0x63, 0x8e, 0x6b, 0x3b, 0x6d, 0x87, 0x91, 0xa2, 0x92, 0xe3,
	0x49, 0x26, 0x4b, 0x4a, 0x76, 0xd9, 0x60, 0x27, 0x81, 0xbe, 0x00, 0x62, 0x5a, 0xd7, 0xa3, 0x3e,
	0x73, 0x3b, 0x57, 0x6d, 0xd3, 0xea, 0x8c, 0xba, 0x8c, 0x1c, 0xd3, 0x3a, 0x7c, 0xa3, 0x2c, 0xfa,
	0x29, 0xe6, 0x5e, 0x4c, 0xdd, 0xe1, 0x64, 0xe0, 0x98, 0xe3, 0x01, 0x73, 0xfb, 0x6c, 0x6a, 0x93,
	0x72, 0xba, 0x82, 0x3d, 0x1e, 0x59, 0x36, 0x23, 0x27, 0xf4, 0x0c, 0xe8, 0xbe, 0xa5, 0xa2, 0x79,
	0xdb, 0xea, 0x31, 0x52, 0x51, 0xee, 0x2a, 0xfe, 0x6e, 0xc2, 0xf8, 0xd4, 0xe5, 0xcc, 0x9e, 0x0c,
	0x1c, 0x52, 0x55, 0xd1, 0x34, 0x92, 0xf2, 0x16, 0x7b, 0xef, 0x10, 0x42, 0xbf, 0x82, 0xe7, 0x0f,
	0xa3, 0x9d, 0xc1, 0xc8, 0x66, 0xe4, 0xb9, 0x9a, 0xb7, 0xcf, 0xd8, 0xb8, 0x3d, 0x30, 0xaf, 0x19,
	0xa1, 0xf4, 0x6b, 0x38, 0x55, 0x8e, 0x57, 0xa6, 0xed, 0x8c, 0xf8, 0xd4, 0xbd, 0x1c, 0x71, 0x35,
	0x11, 0x39, 0x35, 0x5e, 0x43, 0x79, 0xbc, 0x95, 0xb6, 0xf4, 0x24, 0x9a, 0x9b, 0xdb, 0x80, 0x12,
	0x38, 0xb8, 0xc3, 0x38, 0xf9, 0x08, 0x4b, 0x5c, 0x3d, 0xd2, 0x17, 0x50, 0xf8, 0xe0, 0xad, 0xb6,
	0x98, 0x7c, 0x60, 0x65, 0x9e, 0x0a, 0xe3, 0x1f, 0x0d, 0x5e, 0xf5, 0x50, 0xf6, 0x93, 0xca, 0x8b,
	0x78, 0xb8, 0x5d, 0x49, 0x3f, 0x5c, 0x61, 0x1f, 0x63, 0xc1, 0x51, 0x84, 0xc1, 0x46, 0x20, 0x75,
	0xa0, 0x74, 0x87, 0x71, 0x42, 0x08, 0x5d, 0xab, 0x1f, 0x34, 0x8e, 0xcf, 0x5f, 0x67, 0x9f, 0xc0,
	0x67, 0x6a, 0x9b, 0xfd, 0xac, 0x90, 0x6d, 0x64, 0x14, 0xf3, 0x7b, 0xa3, 0xda, 0x5b, 0xa8, 0x3c,
	0x4e, 0x7e, 0xe9, 0xcc, 0xbf, 0xe5, 0xde, 0x68, 0x06, 0x83, 0x6a, 0x0f, 0xe5, 0xae, 0x33, 0xf7,
	0x36, 0x0b, 0xa4, 0x35, 0x28, 0x0a, 0xe9, 0x45, 0xb2, 0xbf, 0xf7, 0xd8, 0x6b, 0x7a, 0x06, 0x87,
	0xb8, 0x99, 0xab, 0x4c, 0x2e, 0xc9, 0xec, 0x94, 0xf1, 0x03, 0x54, 0x7a, 0x28, 0xdf, 0x6d, 0x31,
	0x8a, 0x39, 0x8a, 0xed, 0x4a, 0xaa, 0x96, 0x7f, 0x2a, 0xb9, 0xb3, 0x48, 0x85, 0xf1, 0x3d, 0x90,
	0x1e, 0xca, 0x2b, 0x5f, 0xc8, 0x20, 0x8a, 0x2f, 0x83, 0x48, 0x79, 0x3e, 0x19, 0xd7, 0xa8, 0x43,
	0x25, 0xb1, 0x4a, 0xc6, 0xb2, 0xf0, 0xa3, 0xa4, 0x15, 0xc8, 0xf9, 0xf3, 0x1d, 0x92, 0xf3, 0xe7,
	0xc6, 0x77, 0x50, 0xbd, 0x27, 0x3a, 0xab, 0x40, 0xe0, 0x13, 0xe4, 0x2d, 0xd0, 0x7b, 0xa4, 0x8f,
	0xf1, 0xb5, 0xda, 0xf9, 0x8b, 0xcf, 0xf3, 0x2f, 0xed, 0x61, 0xf9, 0xfe, 0x08, 0x2f, 0xa0, 0x7a,
	0x87, 0xb1, 0x70, 0xbd, 0xcd, 0xdc, 0x4d, 0xc0, 0xec, 0x20, 0x6b, 0xd9, 0x41, 0x3e, 0xed, 0xc9,
	0x4f, 0x54, 0x49, 0x7b, 0x33, 0x4f, 0x94, 0xa0, 0x2f, 0xa1, 0xb8, 0xf4, 0x84, 0xbb, 0x0e, 0xa2,
	0xb4, 0x67, 0x91, 0x1f, 0x2d, 0x3d, 0x31, 0x0c, 0xa2, 0x6c, 0x87, 0x83, 0x6c, 0x87, 0xf3, 0xf7,
	0x0f, 0xee, 0x45, 0x7b, 0x1b, 0x86, 0x41, 0x24, 0x69, 0x17, 0x8a, 0x1c, 0x17, 0xbe, 0x90, 0x18,
	0x51, 0xfd, 0x53, 0xb7, 0x62, 0xed, 0x93, 0x19, 0xe3, 0x59, 0x43, 0xfb, 0x59, 0xbb, 0xe8, 0xc0,
	0x59, 0x10, 0x2d, 0x9a, 0xcb, 0x38, 0xc4, 0x68, 0x85, 0xf3, 0x05, 0x46, 0xbb, 0x82, 0x3f, 0x7e,
	0x5c, 0xf8, 0x72, 0xb9, 0xbd, 0x69, 0xce, 0x82, 0x75, 0xeb, 0x41, 0xba, 0x75, 0xeb, 0xdd, 0x44,
	0xfe, 0x2c, 0xbd, 0xc4, 0x45, 0x4b, 0xdd, 0xf3, 0x37, 0xe9, 0x1f, 0xc2, 0xaf, 0xff, 0x05, 0x00,
	0x00, 0xff, 0xff, 0xf7, 0x27, 0xa3, 0x88, 0x33, 0x06, 0x00, 0x00,
}
